name: modlog
description: "A new Flutter package project."
version: 0.0.5
homepage:

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  equatable: ^2.0.7
  get_it: ^8.0.3
  intl: ^0.20.2
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
